config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  # root "articles#index"

  scope :v1, defaults: { format: :json } do
    resources :raw_events, only: [:index, :create] do
      post :ingest, on: :collection
      get :dump, on: :collection
    end

    resources :shipments, only: [:index]
  end

  scope :wa do
    resources :messages
    resources :conversations, except: [:destroy] do
      patch '/read', on: :member, action: :read
    end
    resources :fb_events, only: [:index]
  end

  get '/', to: 'health#index'
  get 'docs', to: 'docs#index'
  get 'fb-listener', to: 'fb_webhook#index'
  post 'fb-listener', to: 'fb_webhook#ingest'
  get '/export_excel', to: 'conversations#export_excel'

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  # https://dev.to/kputra/rails-postgresql-array-1jn0
  WA_SENDER_PHONE_NUMBER = ENV.fetch('WA_SENDER_PHONE_NUMBER')

  include PhoneNumber
  extend PhoneNumber

  validates :client_phone_number, presence: true
  validates :business_phone_number, presence: true
  validate :check_client_phone_number

  validates_uniqueness_of :client_phone_number, scope: :business_phone_number
  has_many :messages, -> { order(id: :asc) }, dependent: :destroy

  after_initialize :initialize_callback

  before_validation :clean_client_phone_number, on: :create

  def clean_client_phone_number
    self.client_phone_number = sanitize_and_localize_phone_number(client_phone_number)
  end

  def unread_messages?
    !messages.reject(&:outgoing).all?(&:read)
  end

  def self.sync_keywords_with_phone_number
    rows = CSV.read('phone_number_keywords.csv')
    rows.shift
    rows.each do |row|
      keyword, raw_phone_number = row
      client_phone_number = sanitize_and_localize_phone_number(raw_phone_number)
      conversation = Conversation.find_by(client_phone_number: client_phone_number)

      if conversation.present? && !conversation.keywords.include?(keyword)
        conversation.keywords << keyword
        conversation.save
      end
    end
  end

  private

  def initialize_callback
    self.business_phone_number = WA_SENDER_PHONE_NUMBER
  end

  def check_client_phone_number
    return if client_phone_number.nil?

    if client_phone_number.start_with?('60')
      if clean_client_phone_number.length != 12 && clean_client_phone_number.length != 11
        errors.add(:client_phone_number, 'Malaysian numbers require 10-digits followed after the country code and mobile fixed digit')
      end
    elsif client_phone_number.starts_with?('86')
      if client_phone_number.length != 13
        errors.add(:client_phone_number, 'Cannot send message to this number. Check for the correct country code.')
      end
    else
      errors.add(:client_phone_number, 'Invalid phone number')
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: %i[ show edit update destroy read ]
  after_action :read_unread_messages, only: %i[ show ]

  # GET /conversations or /conversations.json
  def index

    @page = params[:page].to_i > 0 ? params[:page].to_i : 1
    @per = 20
    @q = params[:q]
    @date = params[:date]
    @sort = params[:sort]
    business_phone_number = ENV.fetch('WA_SENDER_PHONE_NUMBER')

    @conversation_query = Conversation.includes(:messages)
    @conversation_query = @conversation_query.where("business_phone_number = ? and keywords <> '{}'", business_phone_number)
    if @q.present?
      @conversation_query = @conversation_query
                  .where('client_phone_number LIKE ?', "%#{@q}%").or(
        Conversation.where(":keywords = ANY (keywords)", keywords: @q))
    end

    # https://bhserna.com/query-date-ranges-rails-active-record.html
    if @date.present?
      start_datetime = DateTime.parse(@date)
      end_datetime = start_datetime.at_end_of_day()
      start_utc_offset = Time.parse(start_datetime.to_date.to_s).in_time_zone('America/Mexico_City').utc_offset
      end_utc_offset = Time.parse(end_datetime.to_date.to_s).in_time_zone('America/Mexico_City').utc_offset
      shifted_start_datetime = start_datetime - start_utc_offset.seconds
      shifted_end_datetime = end_datetime - end_utc_offset.seconds
      Rails.logger.info shifted_start_datetime
      Rails.logger.info shifted_end_datetime
      # puts(@tz)
      if @sort.present? && (@sort == "no_keyword" || @sort == "no_outgoing_messages")
        @conversation_query = @conversation_query.where('latest_message_sent_at BETWEEN ? AND ?', shifted_start_datetime, shifted_end_datetime)
      else
        @conversation_query = @conversation_query.where('latest_outgoing_sent_at BETWEEN ? AND ?', shifted_start_datetime, shifted_end_datetime)
      end
    end
    if(!@sort.present? || @sort == "latest_updated" || @sort == "keyword_desc" || @sort == "keyword_asc")
      defaultFilters()
    elsif @sort.present? && @sort == "no_keyword"
      noKeyword()
    elsif @sort.present? && @sort == "unread_message"
      unreadMessage()
    elsif @sort.present? && @sort == "no_outgoing_messages"
      noOutgoingMessages()
    end
    # @total_count = @conversation_query.count
    @total_count = @count
    @page_count = (@total_count / @per) + 1
  end

  # GET /conversations/1 or /conversations/1.json
  def show
    @date = params[:date]
    @q = params[:q]
    @page = params[:page]
    @sort = params[:sort]
    @bulk_insert = params[:bulk] == 'true'
    @message = @conversation.messages.build
    @message_type = @conversation.messages.size.zero? ? Message::TEMPLATE_TYPE : Message::TEXT_TYPE

    @template_params = ['', '', '', '']
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations or /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to conversation_url(@conversation), notice: "Conversation was successfully created." }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1 or /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to conversation_url(@conversation), notice: "Conversation was successfully updated." }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  def read
    unread_messages = @conversation.messages.select(&:unread?)
    Message.where(id: unread_messages.map(&:id)).update_all(read: true)
    url_params = CGI.parse(URI.parse(request.referrer).query || '')
    date = url_params['date'].is_a?(Array) ? url_params['date']&.first : url_params['date']
    q = url_params['q'].is_a?(Array) ? url_params['q']&.first : url_params['q']
    sort = url_params['sort'].is_a?(Array) ? url_params['sort']&.first : url_params['sort']
    page = url_params['page'].is_a?(Array) ? url_params['page']&.first : url_params['page']
    # we grab the messages from the db again
    # so that the view can be refreshed correctly
    # date_init = DateTime.parse(date)
    # at_end_of_day = date_init.at_end_of_day()
    @conversation = Conversation.includes(:messages).find(@conversation.id)

    # @conversation.broadcast_replace(locals: { date: date, q: q, tz: @tz, page: page, sort: sort })
    @conversation.broadcast_replace(locals: { date: date, q: q, tz: 'America/Mexico_City', page: page, sort: sort })

    head :ok
  end

  # DELETE /conversations/1 or /conversations/1.json
  def destroy
    @conversation.destroy

    respond_to do |format|
      format.html { redirect_to conversations_url, notice: "Conversation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def export_excel
    @date = params[:date]
    @sort = params[:sort]
    mark_as_read = params[:mark_as_read]
    if !@date.present?
      start_datetime = DateTime.now
    else 
      start_datetime = DateTime.parse(@date)
    end

    conversation_query = Conversation.includes(:messages)
    business_phone_number = ENV.fetch('WA_SENDER_PHONE_NUMBER')
    conversation_query = conversation_query.where("business_phone_number = ? and keywords <> '{}'", business_phone_number)


    end_datetime = start_datetime.at_end_of_day()
    start_utc_offset = Time.parse(start_datetime.to_date.to_s).in_time_zone('America/Mexico_City').utc_offset
    end_utc_offset = Time.parse(end_datetime.to_date.to_s).in_time_zone('America/Mexico_City').utc_offset
    shifted_start_datetime = start_datetime - start_utc_offset.seconds
    shifted_end_datetime = end_datetime - end_utc_offset.seconds
    Rails.logger.info shifted_start_datetime
    Rails.logger.info shifted_end_datetime
    # puts(@tz)
    conversation_query = conversation_query.select("conversations.*")
    if @sort.present? && (@sort == "no_keyword" || @sort == "no_outgoing_messages")
      if @date.present?
        conversation_query = conversation_query.where('latest_message_sent_at BETWEEN ? AND ?', shifted_start_datetime, shifted_end_datetime)
      end
    else
      if @date.present?
        conversation_query = conversation_query.where('latest_outgoing_sent_at BETWEEN ? AND ?', shifted_start_datetime, shifted_end_datetime)
      end
    end
    # conversation_query =
        if @sort == 'keyword_asc' || @sort == 'keyword_desc'          
          unnesting_arr = Conversation.select('distinct on (conversations.id) id', 'unnest(conversations.keywords)')
          unnesting_arr = unnesting_arr.order(Arel.sql("id, unnest DESC NULLS LAST"))
          conversation_query = conversation_query.joins("join (#{unnesting_arr.to_sql}) as c1 on conversations.id = c1.id")
          conversation_query = conversation_query.order(Arel.sql("unnest DESC NULLS LAST"))
        elsif @sort == 'latest_updated'
          conversation_query = conversation_query.order('latest_message_sent_at DESC NULLS LAST')
        end
      if @sort == 'no_keyword'
        conversation_query = conversation_query.where("keywords = '{}'")
        conversation_query = conversation_query.order('id ASC NULLS LAST')

      elsif @sort == 'unread_message'
        conversation_query = conversation_query.joins("join messages as m1 on conversations.id = m1.conversation_id")
        conversation_query = conversation_query.where("read = false and outgoing = false")
      elsif @sort == "no_outgoing_messages"
        conversation_query = conversation_query.where("latest_outgoing_sent_at IS NULL")
        conversation_query = conversation_query.order('id ASC NULLS LAST')
      end
    conversations = conversation_query.all
    final_conversation = []

    if @sort != 'unread_message' && @sort != 'no_keyword'
      conversations = conversations.each do |conversation|
        conversation.keywords = getKeyword(conversation.keywords, conversation.messages)
      end
    end
    conversations.each do |conversation|
      found = false
      final_conversation.each do |final|
        conversation.keywords.each do |c_keyword|
          final.keywords.each do |f_keyword|
            if c_keyword == f_keyword && (@sort != 'no_keyword')
              found = true
            end
          end
        end
      end
      if !found
        final_conversation.append(conversation)
      end
    end
    if @sort == 'keyword_desc' || @sort == 'unread_message'
      final_conversation = final_conversation.sort { |a, b| ((a.present? && a.keywords.present?) ? a.keywords.last : "" )<=> ((b.present? && b.keywords.present?) ? b.keywords.last : "" )} .reverse!
    elsif @sort == 'keyword_asc'
      final_conversation = final_conversation.sort { |a, b| ((a.present? && a.keywords.present?) ? a.keywords.last : "") <=> ((b.present? && b.keywords.present?) ? b.keywords.last : "" )}
    end
    @items = final_conversation
    if mark_as_read
      if !@date.present?
        Message.update_all "read = 'true'"
      else
        messages = Message.where("created_at BETWEEN ? AND ?", shifted_start_datetime, shifted_end_datetime).update_all "read = 'true'"
      end
    end
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=conversations-#{@date}.xlsx"
      }
      format.html { render :index }
    end
  end

  private

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<%= turbo_stream_from conversation %>
<div id="<%= dom_id conversation %>" class='shadow-xl rounded-lg mt-3 w-3/4 border border-transparent border-[#69B7D3] hover:bg-gray-200' style='position: relative'>
  <div class="flex w-100 justify-between bg-[#69B7D3] rounded-t-lg px-3 py-2 items-center">
    <p class='text-[#333333] text-md'>
      <strong>Client phone number:</strong>
      <%= conversation.client_phone_number %>
    </p>
    <span class='text-[#333333] text-md'>
      <strong>Keywords:</strong>
      <% conversation.keywords.reverse!.each_with_index do |keyword, index| %>
        <% if index < 3 && keyword != "" %>
          <span class="bg-slate-50 text-md px-[5px] py-[3px] rounded-md font-semibold"><%= keyword != "" ? keyword : "N/K"%></span>
        <% end %>
      <% end %>
      <% if conversation.keywords.size > 4 %>
        <span class="bg-slate-50 text-md px-[5px] py-[3px] rounded-md font-semibold">...</span>
      <% end %>
    </span>
    

    <div class="flex w-[300px] justify-end">
      <% if conversation.messages.count{|m| !m.outgoing && !m.read} > 0 %>
          <div class='relative mr-2 text-md rounded-md px-2 bg-[#F16821] text-slate-50 flex justify-center items-center'>
            <div class="absolute top-[-8px] right-[-5px] bg-slate-50 rounded-full w-[15px] h-[15px] text-[0.70rem] text-[#fe8800] flex justify-center items-center" >
              <strong><%= conversation.messages.count{|m| !m.outgoing && !m.read} %></strong>
            </div>
            <%= image_tag 'visibility_off_white_24dp.svg', :class => "h-5 w-auto" %>
          </div>
        <%= form_for conversation, url: read_conversation_url(conversation), method: :patch, remote: true do |form| %>
          <%= form.submit "Mark as Read", class: 'bg-[#AA4F56] text-slate-50 py-1 px-2 rounded-md cursor-pointer text-sm mr-2' %>
        <% end %>
      <% end %>
      <%= link_to 'Open', conversation_path(conversation, date: date, q: q, page: page, sort: sort), data: { turbo_frame: '_top' }, class: 'bg-[#009588] text-slate-50 py-1 px-2 rounded-md cursor-pointer text-sm' %>
    </div>
  </div>

  <% if conversation.messages.size.zero? %>
    <p class='text-[#1c1c27] text-md py-2 px-3'>
      No messages yet
    </p>
  <% else %>
    <p class='text-[#1c1c27] text-md py-1 px-3 max-w-fit break-all'>
      <% if conversation.messages.last.outgoing %>
      You said:
      <% else %>
      Client said:
      <% end %>
      <strong>
      <%= conversation.messages.last.body %>
      </strong>
      at
      <%= conversation.messages.last.sent_at&.in_time_zone('America/Mexico_City') %>
    </p>
  <% end %>

    <% if conversation.messages.select(&:outgoing?).empty? %>
      <p class='text-[#1c1c27] text-sm py-1 px-3'>
        No outgoing message sent yet
      </p>
  <% else %>
      <p class='text-[#1c1c27] text-sm py-1 px-3'>
        First message sent at: <%= conversation.first_message_dispatched_at&.in_time_zone('America/Mexico_City') %>
      </p>
      <p class='text-[#1c1c27] text-sm py-1 px-3'>
        Last message sent at: <%= conversation.latest_outgoing_sent_at&.in_time_zone('America/Mexico_City') %>
      </p>
    <% end %>
</div>

app/views/conversations/_form.html.erb
<%= form_with(model: conversation) do |form| %>
  <% if conversation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
        <% conversation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='mb-2'>
    <%= form.label :client_phone_number, style: "display: block", class: 'block text-sm font-medium leading-6 text-gray-900' %>
    <div class="relative mt-2 rounded-md shadow-sm">
      <%= form.text_field :client_phone_number, placeholder: '60123456789', class: 'block w-full rounded-md border-0 py-1.5 pl-7 pr-20 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-[#69B7D3] sm:text-sm sm:leading-6' %>
    </div>
  </div>

  <div>
    <%= form.submit class: 'w-full bg-[#009588] text-slate-50 p-2 rounded-md cursor-pointer text-md' %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing conversation</h1>

<%= render "form", conversation: @conversation %>

<br>

<div>
  <%= link_to "Show this conversation", @conversation %> |
  <%= link_to "Back to conversations", conversations_path %>
</div>

app/views/conversations/index.html.erb
<div class="bg-white">
 <div class="flex mx-auto w-[72%] justify-between items-end">
  <header class="">
    <nav class="" aria-label="Global">
      <div class="flex lg:flex-1">
        <a href="/wa/conversations" class="">
          <span class="sr-only">Masstrader</span>
          <%= image_tag 'logo_mastrader.jpg', :class => "h-[11rem]" %>
        </a>
      </div>
      <!-- <div class="hidden lg:flex lg:gap-x-12">
        <a href="/wa/conversations" class="text-sm font-semibold leading-6 text-gray-900">Conversations</a>
      </div> -->
      <!-- <div class="hidden lg:flex lg:flex-1 lg:justify-end">
      </div> -->
    </nav>
  </header>
  <div class='flex justify-end'>
    <%= link_to "+ Bulk", new_message_path, class: 'bg-[#009588] text-slate-50 p-2 rounded-md cursor-pointer text-md mr-2' %>
    <%= link_to "+ Conversation", new_conversation_path, class: 'bg-[#009588] text-slate-50 p-2 rounded-md cursor-pointer text-md' %>
  </div>
 </div>
 <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= error %></p>
  <div class="mx-auto flex flex-col relative isolate px-6 lg:px-8 mt-5">
    <div class="mx-auto w-full inline-flex flex-row">
      <%= form_with url: conversations_path, method: :get, :html => {:class => 'flex flex-row justify-end w-[88%]'}, data: { turbo_frame: "conversations-turbo-frame", turbo_action: "advance" } do |form| %>
      <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-[#69B7D3] mr-2">
        <%= form.date_field :date, class: 'block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 md:text-md md:leading-6', value: @date || '', max: Date.today %>
      </div>
      <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-[#69B7D3] mr-2">
        <%= form.text_field :q, placeholder: 'Enter phone number or keyword', class: 'block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 md:text-md md:leading-6 w-[280px]', value: @q || '' %>
      </div>
      <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-[#69B7D3] mr-2">
        <%= form.select :sort, [["Latest updated", "latest_updated"], ["Keyword DESC", "keyword_desc"], ["Keyword ASC", "keyword_asc"], ["Unread Messages", "unread_message"], ["No Outgoing Messages", "no_outgoing_messages"]], { selected: @sort || 'latest_updated' }, { class: 'block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 md:text-md md:leading-6' } %>
      </div>
      <div class="flex">
        <%= form.submit "Search", class: 'bg-[#009588] shadow-sm text-slate-50 p-2 rounded-md cursor-pointer mr-2' %>
      </div>
      <% if @date.present? || params[:sort] == "no_keyword" || params[:sort] == "no_outgoing_messages" || params[:sort] == "no_outgoing_messages" || params[:sort] == "unread_message"%>
        <div class="flex">
          <%= link_to "Download as Excel", export_excel_path(format: :xlsx, date: params[:date], sort: params[:sort]), class: 'bg-[#009588] shadow-sm text-slate-50 p-2 rounded-md cursor-pointer' %>
        </div>
      <% end %>
      <%  if params[:sort] == "unread_message"%>
        <div class="flex pl-[10px]">
          <%= link_to "Mark all as read", export_excel_path(format: :xlsx, date: params[:date], sort: params[:sort], mark_as_read: true), class: 'bg-[#009588] shadow-sm text-slate-50 p-2 rounded-md cursor-pointer',:onclick => 'setTimeout(()=>{location.reload()}, 1000)' %>
        </div>
      <% end %>          
    <% end %>
    </div>
    <%= render partial:"conversations/pagination", date: @date, q: @q, tz: "America/Mexico_City", page: @page, sort: @sort, total_count: @total_count %>
    <div id="conversations" class="flex flex-col items-center mb-[20px]">
      <% @conversations.each do |conversation| %>
        <%= render conversation, date: @date, q: @q, tz: "America/Mexico_City", page: @page, sort: @sort %>
      <% end %>
    </div>
  </div>
</div>
<button id="myBtn" title="Go to top"><a href="#top"><%= image_tag 'up.png', :class => "h-[2rem]" %></a></button>
<script>
// let mybutton = document.getElementById("myBtn");
// const body = document.getElementsByTagName("BODY")[0]
// console.log(body);
// if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
//         mybutton.style.display = "block";
//     } else {
//         mybutton.style.display = "none";
//     }
document.addEventListener("scroll",(evt) => {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("myBtn").style.display = "block";
    } else {
        document.getElementById("myBtn").style.display = "none";
    }
})
</script>

app/views/conversations/new.html.erb
<%= render partial: 'shared/conversation_header', locals: { page: @page, client_phone_number: nil, heading: nil, conversation: nil, date: @date, q: @q, sort: @sort } %>


<div class='w-1/2 mx-auto'>
  <%= render "form", conversation: @conversation %>
</div>

app/views/conversations/show.html.erb
<%= render partial: 'shared/conversation_header', locals: { conversation: @conversation, client_phone_number: @conversation.client_phone_number, heading: 'Conversation', q: @q, date: @date, page: @page, sort: @sort } %>

<div class='w-1/2 mx-auto'>
  <div class='my-2'><strong>Conversation:</strong> <%= @conversation.client_phone_number %></div>
  <div class='my-2'><strong>Keywords:</strong> <%= @conversation.keywords.join(', ') %></div>
  <div data-controller='new-message'>
    <%= render "messages/form", message: @message, conversation: @conversation, message_type: @message_type, template_params: @template_params %>
  </div>
  <div class="mb-[20px]">
    <% @conversation.messages.each do |message| %>
      <% if !message.new_record? %>
        <%= render message, tz: 'America/Mexico_City' %>
      <% end %>
    <% end %>
  </div>
</div>