config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  # root "articles#index"

  scope :v1, defaults: { format: :json } do
    resources :raw_events, only: [:index, :create] do
      post :ingest, on: :collection
      get :dump, on: :collection
    end

    resources :shipments, only: [:index]
  end

  scope :wa do
    resources :messages
    resources :conversations, except: [:destroy] do
      patch '/read', on: :member, action: :read
    end
    resources :fb_events, only: [:index]
  end

  get '/', to: 'health#index'
  get 'docs', to: 'docs#index'
  get 'fb-listener', to: 'fb_webhook#index'
  post 'fb-listener', to: 'fb_webhook#ingest'
  get '/export_excel', to: 'conversations#export_excel'

end

app/models/fb_event.rb
class FbEvent < ApplicationRecord
  validates :data, presence: true

  def incoming_message_event?
    data['entry'].first['changes'].first['value']['messages'].present? rescue false
  end

  def message_delivered_event?
    data['entry'].first['changes'].first['value']['statuses'].first['status'] == 'delivered' rescue false
  end

  def delivered_at_ts
    Time.at(data['entry'].first['changes'].first['value']['statuses'].first['timestamp'].to_i) rescue nil
  end

  def message_sent_event?
    data['entry'].first['changes'].first['value']['statuses'].first['status'] == 'sent' rescue false
  end

  def sent_at_ts
    Time.at(data['entry'].first['changes'].first['value']['statuses'].first['timestamp'].to_i) rescue nil
  end

  def wa_id
    value = data['entry'].first['changes'].first['value']
    wa_id = value['messages'].first['id'] rescue nil
    if wa_id.nil?
      value['statuses'].first['id'] rescue nil 
    else
      wa_id
    end
  end
end

app/controllers/fb_events_controller.rb
class FbEventsController < ApplicationController
  before_action :set_fb_event, only: %i[ show edit update destroy ]

  # GET /fb_events or /fb_events.json
  def index
    @fb_events = FbEvent.all.order(id: :desc)
  end

  # GET /fb_events/1 or /fb_events/1.json
  def show
  end

  # GET /fb_events/new
  def new
    @fb_event = FbEvent.new
  end

  # GET /fb_events/1/edit
  def edit
  end

  # POST /fb_events or /fb_events.json
  def create
    @fb_event = FbEvent.new(fb_event_params)

    respond_to do |format|
      if @fb_event.save
        format.html { redirect_to fb_event_url(@fb_event), notice: "Fb event was successfully created." }
        format.json { render :show, status: :created, location: @fb_event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fb_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fb_events/1 or /fb_events/1.json
  def update
    respond_to do |format|
      if @fb_event.update(fb_event_params)
        format.html { redirect_to fb_event_url(@fb_event), notice: "Fb event was successfully updated." }
        format.json { render :show, status: :ok, location: @fb_event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fb_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fb_events/1 or /fb_events/1.json
  def destroy
    @fb_event.destroy

    respond_to do |format|
      format.html { redirect_to fb_events_url, notice: "Fb event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fb_event
      @fb_event = FbEvent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fb_event_params
      params.require(:fb_event).permit(:data)
    end
end

app/helpers/fb_events_helper.rb
module FbEventsHelper
end

app/views/fb_events/_fb_event.html.erb
<div id="<%= dom_id fb_event %>" class='mb-3'>
  <p><%= fb_event.id %>
  <p>
    <%= fb_event.data.to_json %>
  </p>

</div>

app/views/fb_events/_form.html.erb
<%= form_with(model: fb_event) do |form| %>
  <% if fb_event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fb_event.errors.count, "error") %> prohibited this fb_event from being saved:</h2>

      <ul>
        <% fb_event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.text_field :data %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/fb_events/edit.html.erb
<h1>Editing fb event</h1>

<%= render "form", fb_event: @fb_event %>

<br>

<div>
  <%= link_to "Show this fb event", @fb_event %> |
  <%= link_to "Back to fb events", fb_events_path %>
</div>

app/views/fb_events/index.html.erb
<% @fb_events.each do |fb_event| %>
  <%= render fb_event %>
<% end %>

app/views/fb_events/new.html.erb
<h1>New fb event</h1>

<%= render "form", fb_event: @fb_event %>

<br>

<div>
  <%= link_to "Back to fb events", fb_events_path %>
</div>

app/views/fb_events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fb_event %>

<div>
  <%= link_to "Edit this fb event", edit_fb_event_path(@fb_event) %> |
  <%= link_to "Back to fb events", fb_events_path %>

  <%= button_to "Destroy this fb event", @fb_event, method: :delete %>
</div>